version: '3'

env:
  ENV: '.tmp'
  APACHE_PULSAR_SETUP_POETRY: 'poetry' # path to poetry

dotenv: [ '.env', '{{.ENV}}/.env', '{{.HOME}}/.env' ]

tasks:
  init:
    desc: "Configure poetry and install dependencies"
    cmds:
      - $APACHE_PULSAR_SETUP_POETRY install
      - mkdir -p .tmp
    sources:
      - pyproject.toml
      - poetry.lock
    generates:
      - .venv/bin/python
  run:
    desc: "Run the CLI tool"
    cmds:
      - $APACHE_PULSAR_SETUP_POETRY run python -m apache_pulsar_setup.main {{.CLI_ARGS}}
  clean:
    desc: "Remove virtual environment and temporary artifacts"
    cmds:
      - rm -rf .venv
      - rm -rf dist
      - find . -type d -name "__pycache__" -exec rm -rf {} +
      - echo "Clean complete"